IDIOMAS = {
    "es": {
        "titulo": "Convertidor de Python a EXE",
        "idioma": "Idioma",
        "seleccionar_archivo": "Selecciona tu archivo .py:",
        "seleccionar_icono": "Opcional: Selecciona un ícono (.ico)",
        "buscar": "Buscar",
        "modo_onefile": "Generar un solo archivo (.exe)",
        "tooltip_exe": "Esta opción está deshabilitada porque estás ejecutando la versión empaquetada (.exe).\nSolo está disponible en la versión Python para garantizar una conversión estable.",
        "mostrar_consola": "Mostrar consola (solo si no hay GUI)",
        "boton_convertir": "Convertir a .exe",
        "error": "Error",
        "error_convertidor": "No puedes convertir el mismo archivo del convertidor.",
        "creditos": "Creado por Pablo Otero M. — Septiembre 2025",
        "mensaje_espera": "La conversión ha comenzado. Esto puede tardar unos segundos. Serás notificado cuando finalice."
    },
    "en": {
        "titulo": "Python to EXE Converter",
        "idioma": "Language",
        "seleccionar_archivo": "Select your .py file:",
        "seleccionar_icono": "Optional: Select an icon (.ico)",
        "buscar": "Browse",
        "modo_onefile": "Generate a single .exe file",
        "tooltip_exe": "This option is disabled because you're running the packaged (.exe) version.\nIt is only available in the Python version to ensure stable conversion.",
        "mostrar_consola": "Show console (only if no GUI is detected)",
        "boton_convertir": "Convert to .exe",
        "error": "Error",
        "error_convertidor": "You cannot convert the same file as the converter itself.",
        "creditos": "Created by Pablo Otero M. — September 2025",
        "mensaje_espera": "Conversion has started. This may take a few seconds. You will be notified when it's done."
    },
    "fr": {
        "titulo": "Convertisseur Python en EXE",
        "idioma": "Langue",
        "seleccionar_archivo": "Sélectionnez votre fichier .py :",
        "seleccionar_icono": "Optionnel : Sélectionnez une icône (.ico)",
        "buscar": "Parcourir",
        "modo_onefile": "Générer un seul fichier .exe",
        "tooltip_exe": "Cette option est désactivée car vous exécutez la version empaquetée (.exe).\nElle est uniquement disponible dans la version Python pour garantir une conversion stable.",
        "mostrar_consola": "Afficher la console (uniquement si aucune interface graphique n'est détectée)",
        "boton_convertir": "Convertir en .exe",
        "error": "Erreur",
        "error_convertidor": "Vous ne pouvez pas convertir le même fichier que le convertisseur lui-même.",
        "creditos": "Créé par Pablo Otero M. — Septembre 2025",
        "mensaje_espera": "La conversion a commencé. Cela peut prendre quelques secondes. Vous serez averti une fois terminée."
    },
    "de": {
        "titulo": "Python-zu-EXE-Konverter",
        "idioma": "Sprache",
        "seleccionar_archivo": "Wähle deine .py-Datei:",
        "seleccionar_icono": "Optional: Wähle ein Icon (.ico)",
        "buscar": "Durchsuchen",
        "modo_onefile": "Eine einzelne .exe-Datei erzeugen",
        "tooltip_exe": "Diese Option ist deaktiviert, da du die gepackte (.exe) Version ausführst.\nSie ist nur in der Python-Version verfügbar, um eine stabile Konvertierung zu gewährleisten.",
        "mostrar_consola": "Konsole anzeigen (nur wenn keine GUI erkannt wird)",
        "boton_convertir": "In .exe konvertieren",
        "error": "Fehler",
        "error_convertidor": "Du kannst nicht dieselbe Datei wie den Konverter konvertieren.",
        "creditos": "Erstellt von Pablo Otero M. — September 2025",
        "mensaje_espera": "Die Konvertierung hat begonnen. Dies kann einige Sekunden dauern. Du wirst benachrichtigt, wenn sie abgeschlossen ist."
    },
    "uk": {
        "titulo": "Конвертер Python у EXE",
        "idioma": "Мова",
        "seleccionar_archivo": "Виберіть ваш файл .py:",
        "seleccionar_icono": "Опціонально: Виберіть іконку (.ico)",
        "buscar": "Огляд",
        "modo_onefile": "Створити один .exe файл",
        "tooltip_exe": "Ця опція вимкнена, оскільки ви використовуєте упаковану версію (.exe).\nВона доступна лише у версії Python для стабільного перетворення.",
        "mostrar_consola": "Показати консоль (лише якщо GUI не виявлено)",
        "boton_convertir": "Конвертувати в .exe",
        "error": "Помилка",
        "error_convertidor": "Неможливо конвертувати той самий файл, що і сам конвертер.",
        "creditos": "Створено Пабло Отера М. — Вересень 2025",
        "mensaje_espera": "Конвертація розпочалася. Це може зайняти кілька секунд. Ви отримаєте сповіщення після завершення."
    },
    "zh": {
        "titulo": "Python 转换为 EXE",
        "idioma": "语言",
        "seleccionar_archivo": "选择你的 .py 文件：",
        "seleccionar_icono": "可选：选择一个图标 (.ico)",
        "buscar": "浏览",
        "modo_onefile": "生成单个 .exe 文件",
        "tooltip_exe": "此选项已禁用，因为您正在运行打包的 (.exe) 版本。\n仅在 Python 版本中可用，以确保稳定转换。",
        "mostrar_consola": "显示控制台（仅当未检测到 GUI 时）",
        "boton_convertir": "转换为 .exe",
        "error": "错误",
        "error_convertidor": "无法转换与转换器本身相同的文件。",
        "creditos": "由 Pablo Otero M. 创建 — 2025年9月",
        "mensaje_espera": "转换已开始。可能需要几秒钟。完成后将通知您。"
    }
}